authentication/urls.py
from authentication import views
from django.urls import path

app_name = 'authentication'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_page, name='register'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from  django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('network.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('posts/', include('posts.urls')),
    path('m/', include('messanger.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

messanger/urls.py
from django.contrib import admin
from django.urls import path, include
from messanger import views


app_name = 'messanger'

urlpatterns = [
    path('', views.ChatsView.as_view(), name='show_chats'),
    path('create_chat/', views.ChatsView.as_view(), name='create_chat'),
    path('<int:chat_id>/', views.MessagesView.as_view(), name='messages'),
]

network/urls.py
from django.contrib import admin
from django.urls import path, include
from network import views


app_name = 'network'

urlpatterns = [
    path('', views.index, name='index'),
    # path('profile', views.my_profile, name='my_profile'),

    # path('user/<int:user_id>/', views.user_profile_by_id, name='user_profile_by_id'),
    # path('user/<int:user_id>/about', views.user_about, name='user_about'),
    # path('user/<int:user_id>/friends', views.user_friends, name='user_friends'),
    # path('user/<int:user_id>/photos', views.ProfilePhotosView.as_view(), name='user_photos'),
    # path('user/<int:user_id>/videos', views.user_videos, name='user_videos'),

    path('user/<int:user_id>/', views.ProfilePage.as_view(), name='user_profile_by_id'),
    path('user/<int:user_id>/about', views.ProfilePage.as_view(template_name='profile_about.html'), name='user_about'),
    path('user/<int:user_id>/friends', views.ProfilePage.as_view(template_name='profile_friends.html'), name='user_friends'),
    path('user/<int:user_id>/photos', views.ProfilePhotosView.as_view(), name='user_photos'),
    path('user/<int:user_id>/videos', views.ProfilePage.as_view(template_name='profile_videos.html'), name='user_videos'),

    # path('user/<str:username>/', views.user_profile_by_username, name='user_profile_by_username'),
    # path('about', views.about, name='about'),
    path('feed', views.feed, name='feed'),
    path('videos', views.videos, name='videos'),
    path('photos', views.photos, name='photos'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('theme', views.change_theme, name='change_theme'),
    path('friends', views.friends, name='friends'),
    path('search', views.search, name='search'),
    path('upload_photo', views.ProfilePhotosView.as_view(), name='upload_photo'),
    path('follow/<int:user_id>/', views.follow, name='follow'),
    path('unfollow/<int:user_id>/', views.unfollow, name='unfollow'),
]

posts/urls.py
from django.contrib import admin
from django.urls import path, include
from posts import views


app_name = 'posts'

urlpatterns = [
    path('post_like/', views.post_like, name='post_like'),
    path('post/<int:post_id>/', views.post_by_id, name='post_by_id'),
    path('create_post', views.create_post, name='create_post')
]

messanger/models.py
from django.contrib.auth.models import User
from django.db import models


class Chat(models.Model):
    members = models.ManyToManyField(User, related_name='user_chats')

    def __str__(self):
        users = self.members.all()
        return f'{users[0]} ______ {users[1]}'


class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_messages')
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE, related_name='chat_messages')
    text = models.CharField(max_length=1280)
    creation_time = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    class Meta:
        ordering = ['creation_time']

    def __str__(self):
        for user in self.chat.members.all():
            if user != self.sender:
                break
        return f'{self.sender.username} --> {user.username} ___ {self.text}'

posts/models.py
from django.db.models.signals import pre_save
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db import models


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    text = models.CharField(max_length=1280, blank=True)
    post_pic = models.ImageField(upload_to='posts', blank=True)
    creation_time = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, through="PostLike", related_name='post_likes')
    comments = models.ManyToManyField(User, through="PostComment", related_name='post_comments')
    reposts = models.ManyToManyField(User, through="RePost", related_name='reposts')
    is_tiny = models.BooleanField(default=False)

    class Meta:
        ordering = ['-id']


@receiver(pre_save, sender=Post)
def name_uppercase(sender, instance, *args, **kwargs):
    if len(instance.text) < 42 and not instance.post_pic:
        instance.is_tiny = True


class PostLike(models.Model):
    user_like = models.ForeignKey(User, on_delete=models.CASCADE)
    post_like = models.ForeignKey(Post, on_delete=models.CASCADE)
    creation_time = models.DateTimeField(auto_now_add=True)


class PostComment(models.Model):
    user_comment = models.ForeignKey(User, on_delete=models.CASCADE)
    post_comment = models.ForeignKey(Post, on_delete=models.CASCADE)
    creation_time = models.DateTimeField(auto_now_add=True)
    text = models.CharField(max_length=1280, blank=True)


class RePost(models.Model):
    user_repost = models.ForeignKey(User, on_delete=models.CASCADE)
    post_repost = models.ForeignKey(Post, on_delete=models.CASCADE)
    creation_time = models.DateTimeField(auto_now_add=True)

messanger/forms.py
from django import forms
from .models import Chat, Message


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('sender', 'text', 'chat')

messanger/views.py
from django.shortcuts import render, redirect
from django_registration.forms import User
from .models import Chat, Message
from .forms import MessageForm
from django.views import View
from posts.models import Post


class ChatsView(View):
    def get(self, request):
        if not request.user.is_authenticated:
            return render(request, 'login.html')

        rem = []
        chats = Chat.objects.filter(members__in=[request.user])
        for chat in chats:
            if chat.chat_messages.count() == 0:
                rem.append(chat.id)
        chats = chats.exclude(id__in=rem)
        chats = sorted(chats,
                       key=lambda c: c.chat_messages.last().id,
                       reverse=True)
        return render(request, 'messanger.html', {'user': request.user, 'chats': chats})

    def post(self, request):
        if not request.user.is_authenticated:
            return render(request, 'login.html')

        user_id = request.POST['user_id']
        companion = User.objects.get(id=user_id)
        chat = Chat.objects.filter(members__in=[request.user]).filter(members__in=[companion]).distinct().first()
        if not chat:
            chat = Chat.objects.create()
            chat.members.add(request.user)
            chat.members.add(companion)

        return redirect('messanger:messages', chat_id=chat.id)


class MessagesView(View):
    def get(self, request, chat_id):
        if not request.user.is_authenticated:
            return render(request, 'login.html')

        try:
            chat = Chat.objects.get(id=chat_id, members__in=[request.user])
            if chat.chat_messages.count() != 0:
                for message in chat.chat_messages.filter(is_read=False):
                    if message.sender != request.user:
                        message.is_read = True
                        message.save()
        except Chat.DoesNotExist:
            chat = None

        chats = sorted(Chat.objects.filter(members__in=[request.user]),
                       key=lambda c: 999999 if c.chat_messages.count() == 0 else c.chat_messages.last().id,
                       reverse=True)
        context = {
            'user': request.user,
            'chats': chats,
            'main_chat': chat
        }
        return render(request, 'messanger.html', context)

    def post(self, request, chat_id):
        if not request.user.is_authenticated:
            return render(request, 'login.html')

        try:
            redirect_to = request.GET.get('next', '')
        except Exception:
            redirect_to = 'network:feed'

        message_form = MessageForm(request.POST)
        if message_form.is_valid():
            message_form.save()

        return redirect(redirect_to)

posts/views.py
from django.shortcuts import render, redirect
from posts.models import Post, PostLike


def create_post(request):
    redirect_to = 'network:feed'
    if request.method == 'POST':
        if not request.user.is_authenticated:
            return render(request, 'login.html')
        try:
            redirect_to = request.GET.get('next', '')
        except Exception:
            redirect_to = 'network:feed'

        post = Post(user=request.user, text=request.POST['text'])
        post.save()

    return redirect(redirect_to)


def post_by_id(request):
    if not request.user.is_authenticated:
        return render(request, 'login.html')

    return render(request, 'profile_posts.html', {'user': request.user})


def post_like(request):
    if not request.user.is_authenticated:
        return render(request, 'login.html')

    try:
        redirect_to = request.GET.get('next', '')
        post_id = request.GET.get('post_id', '')
        post = Post.objects.get(id=post_id)
        try:
            like = PostLike.objects.get(user_like=request.user, post_like=post)
            like.delete()
        except Exception:
            like = PostLike(user_like=request.user, post_like=post)
            like.save()
    except Exception:
        redirect_to = 'network:feed'

    return redirect(redirect_to)

templates/base_profile.html
{% extends 'base.html' %}
{% block title %}Профиль{% endblock title %}
{% block container %}


            <div class="col-12 col-sm-12 col-md-12 col-lg-9 col-xl-10">
                <div class="row">
                    <div class="col-12 grid-margin">
                        <div class="profile-header">
                            <div class="cover">
                                <div class="gray-shade"></div>
                                <figure>
                                    <img src="https://bootdey.com/img/Content/bg1.jpg" class="img-fluid" alt="profile cover">
                                </figure>
                                <div class="cover-body d-flex justify-content-between align-items-center">
                                    <div>
                                        <img class="profile-pic"
                                             src="{{ user.profile.profile_pic.url }}"
                                             alt="profile">
                                        <span class="profile-name">{% if user.profile %}{{ user.profile.name }} {{ user.profile.surname }}{% else %}{{user.username}}{% endif %}</span>
                                    </div>
                                    <div class="d-none d-md-block">
                                        {% if user == request.user %}
                                        <button class="btn btn-primary btn-icon-text btn-edit-profile">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                                 viewBox="0 0 24 24"
                                                 fill="none" stroke="currentColor" stroke-width="2"
                                                 stroke-linecap="round"
                                                 stroke-linejoin="round" class="feather feather-edit btn-icon-prepend">
                                                <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path>
                                                <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path>
                                            </svg>
                                            <a style="color:#FFFFFF; text-decoration:none;" href="{% url 'network:edit_profile' %}">Редактировать</a>
                                        </button>
                                        {% else %}
                                        <form action="{% url 'messanger:create_chat' %}" method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="user_id" value="{{ user.id }}">
                                        <button type="submit" class="btn btn-primary btn-icon-text btn-edit-profile">
<!--                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"-->
<!--                                                 viewBox="0 0 24 24"-->
<!--                                                 fill="none" stroke="currentColor" stroke-width="2"-->
<!--                                                 stroke-linecap="round"-->
<!--                                                 stroke-linejoin="round" class="feather feather-edit btn-icon-prepend">-->
<!--                                                <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path>-->
<!--                                                <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path>-->
<!--                                            </svg>-->
                                            Написать
                                        </button>
                                        </form>
                                        {% if relation == 'friend' %}
                                        <a style="color:#FFFFFF; text-decoration:none;" href="{% url 'network:unfollow' user.id %}">
                                        <button style="cursor: default;" class="btn btn-primary btn-icon-text btn-edit-profile">
                                            Удалить из друзей
                                        </button></a>
                                        {% elif relation == 'follow' %}
                                        <a style="color:#FFFFFF; text-decoration:none;" href="{% url 'network:unfollow' user.id %}">
                                        <button style="cursor: default;" class="btn btn-primary btn-icon-text btn-edit-profile">
                                            Отписаться
                                        </button></a>
                                        {% elif relation == 'follower' %}
                                        <a style="color:#FFFFFF; text-decoration:none;" href="{% url 'network:follow' user.id %}">
                                        <button class="btn btn-primary btn-icon-text btn-edit-profile">
                                            Принять заявку
                                        </button></a>
                                        {% else %}
                                        <a style="color:#FFFFFF; text-decoration:none;" href="{% url 'network:follow' user.id %}">
                                        <button class="btn btn-primary btn-icon-text btn-edit-profile">
                                            Подписаться
                                        </button></a>
                                        {% endif %}
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <div class="header-links">
                                <ul class="links d-flex align-items-center mt-3 mt-md-0">
                                    <li class="header-link-item d-flex align-items-center {% block timeline %}{% endblock timeline %}">
                                        <a href="{% url 'network:user_profile_by_id' user.id %}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                             viewBox="0 0 24 24"
                                             fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                             stroke-linejoin="round" class="feather feather-columns mr-1 icon-md">
                                            <path d="M12 3h7a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-7m0-18H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h7m0-18v18"></path>
                                        </svg></a>
                                        <a class="pt-1px d-none d-xl-block" href="{% url 'network:user_profile_by_id' user.id %}">Лента</a>
                                    </li>
                                    <li class="header-link-item ml-3 pl-3 border-left d-flex align-items-center  {% block about %}{% endblock about %}">
                                        <a href="{% url 'network:user_about' user.id %}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                             viewBox="0 0 24 24"
                                             fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                             stroke-linejoin="round" class="feather feather-user mr-1 icon-md">
                                            <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
                                            <circle cx="12" cy="7" r="4"></circle>
                                        </svg></a>
                                        <a class="pt-1px d-none d-xl-block" href="{% url 'network:user_about' user.id %}">Подробнее</a>
                                    </li>
                                    <li class="header-link-item ml-3 pl-3 border-left d-flex align-items-center {% block friends %}{% endblock friends %}">
                                        <a class="pt-1px d-none d-xl-block" href="{% url 'network:user_friends' user.id %}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                             viewBox="0 0 24 24"
                                             fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                             stroke-linejoin="round" class="feather feather-users mr-1 icon-md">
                                            <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
                                            <circle cx="9" cy="7" r="4"></circle>
                                            <path d="M23 21v-2a4 4 0 0 0-3-3.87"></path>
                                            <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
                                        </svg></a>
                                        <a class="pt-1px d-none d-xl-block" href="{% url 'network:user_friends' user.id %}">Друзья&nbsp;</a>
                                        <span class="text-muted tx-12"> 3,765</span>
                                    </li>
                                    <li class="header-link-item ml-3 pl-3 border-left d-flex align-items-center {% block photos %}{% endblock photos %}">
                                        <a class="pt-1px d-none d-xl-block" href="{% url 'network:user_photos' user.id %}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                             viewBox="0 0 24 24"
                                             fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                             stroke-linejoin="round" class="feather feather-image mr-1 icon-md">
                                            <rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect>
                                            <circle cx="8.5" cy="8.5" r="1.5"></circle>
                                            <polyline points="21 15 16 10 5 21"></polyline>
                                        </svg></a>
                                        <a class="pt-1px d-none d-xl-block" href="{% url 'network:user_photos' user.id %}">Фото</a>
                                    </li>
                                    <li class="header-link-item ml-3 pl-3 border-left d-flex align-items-center {% block videos %}{% endblock videos %}">
                                        <a class="pt-1px d-none d-xl-block" href="{% url 'network:user_videos' user.id %}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                             viewBox="0 0 24 24"
                                             fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                             stroke-linejoin="round" class="feather feather-video mr-1 icon-md">
                                            <polygon points="23 7 16 12 23 17 23 7"></polygon>
                                            <rect x="1" y="5" width="15" height="14" rx="2" ry="2"></rect>
                                        </svg></a>
                                        <a class="pt-1px d-none d-xl-block" href="{% url 'network:user_videos' user.id %}">Видео</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                    <!-- ========= // Posts \\ ========= -->

                    {% block profile %}

                    {% endblock profile %}

                    <!-- ======= // left cards \\ ======= -->

            </div>


{% endblock container %}

templates/friends.html
{% extends 'base.html' %}
{% block title %}Друзья{% endblock title %}
{% block container %}


<div class="col-12 col-sm-12 col-md-12 col-lg-9 col-xl-10">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-8 col-xl-7">
            <div class="row">
                <div class="col-12 grid-margin">
                    <div class="card rounded">
                        <div class="card-child">
                            <form action="{% url 'network:search' %}" method="get">
                                <input type="text" class="profile post" name="text" placeholder="Люди и сообщества" autocomplete="off"></label>
                                <br><input type="submit" style="margin: 0 180px;" class="centering btn btn-primary btn-icon-text btn-edit-profile" value="Поиск">
                            </form>
                        </div>
                    </div>
                </div>
                {% if search %}
                    <div class="col-12 grid-margin">
                        <div class="card rounded">
                            <div class="card-child">
                                {% for user in users %}
                                    <a href="{% url 'network:user_profile_by_id' user.id %}" style="cursor: pointer;" class="message list-group-item list-group-item-action">
                                        <div class="d-flex align-items-start">
                                            <img class="img-xs rounded-circle"
                                                 src="{{ user.profile.profile_pic.url }}" height="40"
                                                 class="img-xs rounded-circle mr-1" width="40">
                                            <div class="flex-grow-1 ml-3">
                                                {{ user.profile.name }} {{ user.profile.surname }}
                                            </div>
                                        </div>
                                    </a>
                                {% endfor %}
                                {% if not users %}
                                    <div class="d-flex align-items-start">Ничего не найдено</div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% elif not count %}
                    <div class="col-12 grid-margin">
                        <div class="card rounded">
                            <div class="card-child">
                                <div class="d-flex align-items-start">Список друзей пуст</div>
                            </div>
                        </div>
                    </div>
                {% else %}
                    {% if friends %}
                    <div class="col-12 grid-margin">
                        <div class="card rounded">
                            <div class="card-child">
                                <div class="d-flex align-items-start">Друзья</div>
                                {% for friend in friends %}
                                <a href="{% url 'network:user_profile_by_id' friend.user.id %}" style="cursor: pointer;" class="message list-group-item list-group-item-action">
                                    <div class="d-flex align-items-start">
                                        <img class="img-xs rounded-circle"
                                             src="{{ friend.profile_pic.url }}" height="40"
                                             class="img-xs rounded-circle mr-1" width="40">
                                        <div class="flex-grow-1 ml-3">
                                            {{ friend.name }} {{ friend.surname }}
                                        </div>
                                    </div>
                                </a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% if follows %}
                    <div class="col-12 grid-margin">
                        <div class="card rounded">
                            <div class="card-child">
                                <div class="d-flex align-items-start">Подписки</div>
                                {% for follow in follows %}
                                <a href="{% url 'network:user_profile_by_id' follow.user.id %}" style="cursor: pointer;" class="message list-group-item list-group-item-action">
                                    <div class="d-flex align-items-start">
                                        <img class="img-xs rounded-circle"
                                             src="{{ follow.profile_pic.url }}" height="40"
                                             class="img-xs rounded-circle mr-1" width="40">
                                        <div class="flex-grow-1 ml-3">
                                            {{ follow.name }} {{ follow.surname }}
                                        </div>
                                    </div>
                                </a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% if followers %}
                    <div class="col-12 grid-margin">
                        <div class="card rounded">
                            <div class="card-child">
                                <div class="d-flex align-items-start">Подписчики</div>
                                {% for follower in followers %}
                                <a href="{% url 'network:user_profile_by_id' follower.user.id %}" style="cursor: pointer;" class="message list-group-item list-group-item-action">
                                    <div class="d-flex align-items-start">
                                        <img class="img-xs rounded-circle"
                                             src="{{ follower.profile_pic.url }}" height="40"
                                             class="img-xs rounded-circle mr-1" width="40">
                                        <div class="flex-grow-1 ml-3">
                                            {{ follower.name }} {{ follower.surname }}
                                        </div>
                                    </div>
                                </a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    {% endif %}
                {% endif %}
            </div>
        </div>
        {% include "left_cards.html" %}
    </div>
</div>


{% endblock container %}

templates/login.html
{% extends 'base_auth.html' %}
{% block title %}Вход{% endblock title %}
{% block container %}


    <div id="formContent">
        <!-- Tabs Titles -->
        <h2 class="active"> Вход </h2>
        <h3 class="inactive underlineHover">
            <a class="underlineHover" href="../register"><b> Регистрация </b></a>
        </h3>
        <!-- Login Form -->
        <form action="{% url 'authentication:login' %}" method="post">
            {% csrf_token %}
            <input type="text" id="username" class="fadeIn second" name="username" placeholder="логин">
            <input type="password" id="password" class="fadeIn third" name="password" placeholder="пароль">
            <input type="submit" class="fadeIn fourth" value="Войти">
        </form>
        {% for message in messages %}
            <p>{{message}}</p>
        {% endfor %}
        <!-- Remind Passowrd -->
        <a class="underlineHover" href="#">Забыли пароль?</a><br><br>
    </div>


{% endblock container %}

templates/my_photos.html
{% extends 'base.html' %}
{% block title %}Фотографии{% endblock title %}
{% block container %}


<div class="col-12 col-sm-12 col-md-12 col-lg-9 col-xl-10">
    <div class="row">
        <div class="col-12">
            <div class="row">
                <div class="col-12 grid-margin">
                    {% include "photos.html" %}
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock container %}

templates/photos.html
<div class="card rounded">
    <div class="card-child">
        {% if request.user.is_authenticated and request.user == user %}
        <form action="{% url 'network:upload_photo' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="hidden" name="page_owner_id" value="{{ user.id }}">
            <input type="hidden" name="description" value="">
            <input type="hidden" name="user" value="{{ request.user.id }}">
            <p><label class="input-file"><input type="file" name="image"><span>Выберите фото</span></label>
            <button style="display: none;" id="upload" type="submit" class="btn btn-primary btn-icon-text btn-edit-profile">Добавить
            </button></p><br>
        </form>
        {% endif %}
        {% if not photos %}
            <div class="d-flex align-items-start">Фотографий нет</div>
        {% endif %}
        {% for photo in photos %}
            <img style="height:200px; padding: 5px;" class="profile-pic" src="{{ photo.image.url }}" alt="profile">
        {% endfor %}
    </div>
</div>